# Generated by Django 3.2 on 2021-04-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='N/A', max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('nickname', models.CharField(default='N/A', max_length=120)),
                ('email', models.CharField(default='N/A', max_length=120)),
                ('phone', models.CharField(default='N/A', max_length=20)),
                ('address', models.TextField(default='N/A')),
                ('image', models.ImageField(blank=True, null=True, upload_to='note/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
    ]
